# Generated by Django 5.0.6 on 2024-06-25 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_delete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='table',
            name='table_email',
            field=models.EmailField(default='email@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='table',
            name='table_phone',
            field=models.CharField(default='+44 20 7123 4567', help_text='Enter your phone number', max_length=100),
        ),
        migrations.AddField(
            model_name='table',
            name='table_time',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
