# Generated by Django 5.0.6 on 2024-07-02 15:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_table_user_alter_table_table_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
